global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
        
scrape_configs:
  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq_exporter:9419"]

rule_files:
  - /etc/prometheus/rabbitmq.rules.yml