{
 "title": "Monitor Queue",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Service", "label": "Search Service", "query": { "query": "label_values(service)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queue",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_queues", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Consumers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_consumers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Channels",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_channels", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ready messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready_global",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unacknowledged Messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_unacknowledged_global",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(queue) (rabbitmq_queue_memory)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "By Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Consumers by Service",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service) (rabbitmq_service_consumers_sum{service=~\"$Service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unack Messages by Service",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service) (rabbitmq_service_messages_unack_sum{service=~\"$Service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready Messages by Service",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service) (rabbitmq_service_messages_ready_sum{service=~\"$Service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Messages by Service",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service) (rabbitmq_service_messages_total_sum{service=~\"$Service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "By Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Consumers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(queue) (rabbitmq_queue_consumers_with_service{service=~\"$Service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "sum by(queue) (rabbitmq_queue_messages_total_with_service{service=~\"$Service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by(queue) (rabbitmq_queue_messages_ready_with_service{service=~\"$Service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unacked Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "sum by(queue) (rabbitmq_queue_messages_unack_with_service{service=~\"$Service\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}